/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import io.vavr.Tuple;
import io.vavr.collection.List;
import lombok.val;
import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testLombokStuff(){
        val some = new ArrayList<>();
        some.add("str");
        some.forEach(System.out::println);
    }

    @Test
    public void tupleTest(){
        val tuple = Tuple.of(1, "val");
        assertEquals((long)1, (long)tuple._1);
        assertEquals("val", tuple._2);
        val swap = tuple.map(
                i -> Integer.toString(i),
                str -> str.length()
        );

        assertEquals("1", swap._1);
        assertEquals((long)3, (long)swap._2);
    }

    @Test
    public void testList(){
        List.of(1,2,3,4).forEach(System.out::println);
    }
}
