import beans.BeanOne;
import beans.BeanTwo;
import lombok.val;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void doOne(){


    }

    public static void main(String[] args) {
       doOne();
    }
}
